backend/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.views.static import serve
# from rest_framework_jwt.views import obtain_jwt_token # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('auth/', obtain_jwt_token), # 追加(ログイン認証)
    path('api/', include('google_app.api.urls')),
    path("", include('google_app.urls')), # 追加
    re_path('media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
]

google_app/api/urls.py
from django.urls import path
from google_app.api import views

urlpatterns = [
    path("user/", views.ListView.as_view(), name="user"),
    path("user/<int:pk>", views.DetailView.as_view(), name="detail"),
    path("lifeexpectancy/", views. ListViewLife.as_view(), name="life"),
]

google_app/urls.py
from django.urls import path
from . import views
from google_app.views import IndexView,Login,AccountRegistration,home,Logout


app_name = 'google_app'
urlpatterns = [
    # path('',IndexView.as_view(),name='index'),
    path('',Login,name = 'Login'),
    path('logout',Logout,name = 'Logout'),
    path('register',AccountRegistration.as_view(),name = 'register'),
    path('home/<int:pk>',home,name= "home")
    ]

google_app/models.py
from calendar import calendar
from distutils.command.upload import upload
from email.policy import default
from statistics import mode
from django.db import models

# ユーザー認証
from django.contrib.auth.models import User

# from django.contrib.postgres.fields import JSONField
# from django_mysql.models import ListCharField

# Create your models here.
class Accounts(models.Model):
    use_in_migrations = True
    #ユーザー認証のインスタンス
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    GENDER_CHOICES = (
    (1, '男性'),
    (2, '女性'),
    (3, 'Xジェンダー'),
    )

    old = models.IntegerField(default = 0)
    sex = models.IntegerField(choices=GENDER_CHOICES)
    data = models.JSONField(default = {"name":"mamoru"})
    datalist = models.JSONField(default = {"list":["list"]})
    account_image = models.ImageField(blank=True)
    
    class Meta:
       app_label = 'google_app'

    def __str__(self):
        return self.user.username


class LifeExpectancy(models.Model):
    year = models.IntegerField(default=2022)
    old_list_men = models.JSONField(default={0:81})
    old_list_women = models.JSONField(default={0:89})

    class Meta:
        app_label = "google_app"
    def __str__(self):
        return self.name

google_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Accounts

# フォームクラス作成
class AccountForm(forms.ModelForm):
    # パスワード入力：非表示対応 forms.PasswordInput()
    password = forms.CharField(widget=forms.PasswordInput(),label="パスワード")

    class Meta():
        # ユーザー認証
        model = User
        # フィールド指定
        fields = ('username','email','password')
        # フィールド名指定
        labels = {'username':"ユーザーID",'email':"メール",'password':"パスワード"}

# 新規登録フォーム
class AddAccountForm(forms.ModelForm):
    class Meta():
        # モデルクラスを指定
        model = Accounts
        fields = ('old','sex','account_image')
        labels = {'old':"年齢",'sex':"性別",'account_image':"プロフィール画像"}

google_app/api/views.py
from rest_framework import generics
from google_app.models import Accounts,LifeExpectancy
from google_app.api.serializers import AccountsSerializer,LifeSeializer

class ListView(generics.ListCreateAPIView):
    queryset = Accounts.objects.all().order_by('-id')
    serializer_class = AccountsSerializer
    filter_fields = ('user',)  #追加
    def get_queryset(self):
        """
        Optionally restricts the returned purchases to a given user,
        by filtering against a `username` query parameter in the URL.
        """
        queryset = Accounts.objects.all()
        userid = self.request.query_params.get('user')
        if userid is not None:
            queryset = queryset.filter(user=userid)
        return queryset
    
class DetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Accounts.objects.all()
    serializer_class = AccountsSerializer

class ListViewLife(generics.ListCreateAPIView):
    queryset =  LifeExpectancy.objects.all()
    serializer_class = LifeSeializer

google_app/views.py
from ctypes.wintypes import INT
from email import header
from http.client import UnimplementedFileMode
import imp
import re
from urllib import request
from wsgiref import validate
from django.shortcuts import render
from django.views.generic import TemplateView

#calender function
import datetime
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
import json
import datetime, re

# api
from google_app.api.serializers import AccountsSerializer
import requests

#googleカレンダー
from .calender_api.client_api import get_time

# ログイン・ログアウト処理に利用
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import AccountForm, AddAccountForm

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/calendar.readonly']

# Create your views here.
class IndexView(TemplateView):
    template_name = "index.html"

    def post(self,request):
        if request.POST:
            lists = get_time()
            print(type(lists))
            if lists:
                calender_list = [k for k,v in lists.items()]
        print(calender_list)
        #apiに追加する処理
        validate_data = {
            "name":"kazuya",
            "email":"kazuya@gmail.com",
            "old":23,
            "sex":"男",
            "data":lists,
            "datalist":{},
            }
        print(validate_data)
        #apiデータ追加その1
        # user = UserSerializer(data = json.dumps(validate_data))
        # user.save()

        #apiデータ追加その2
        headers = {"Content-Type" : "application/json"}
        #新規追加
        requests.post("http://127.0.0.1:8000/api/usr/",data=json.dumps(validate_data),headers=headers)

        # 編集
        # responce = requests.put("http://127.0.0.1:8000/api/googleCalender/1",data=json.dumps(validate_data),headers=headers)
        ans = {'lists':lists}
        return self.render_to_response(ans)
        # return render(request, 'index.html',lists)


def Login(request):
    # POST
    if request.method == 'POST':
        # フォーム入力のユーザーID・パスワード取得
        ID = request.POST.get('userid')
        Pass = request.POST.get('password')

        # Djangoの認証機能
        headers = {"Content-Type" : "application/json"}
        user = authenticate(username=ID, password=Pass)

        print("user",user.id)
        user_data = requests.get("http://127.0.0.1:8000/api/user/?user={}".format(user.id),headers=headers)
        dict = json.loads(user_data.content.decode('utf-8'))
        print(dict)
        id = dict["results"][0]["id"]
        
        # googleカレンダー情報取得
        lists = get_time(is_registered = True)
        this_month = datetime.date.today().month
        dict["results"][0]["data"][0][this_month] = lists
        validate_data = {
            "old":int(dict["results"][0]["old"]),
            "sex":dict["results"][0]["sex"],
            "data":dict["results"][0]["data"][0],
            "datalist":{},
            "user":user.id,
        }
        requests.put("http://127.0.0.1:8000/api/user/{}".format(int(id)),data=json.dumps(validate_data),headers=headers)
        
        # ユーザー認証
        if user:
            #ユーザーアクティベート判定
            if user.is_active:
                # ログイン
                login(request,user)
                # ホームページ遷移
                return HttpResponseRedirect(reverse('google_app:home',kwargs={'pk':id}))
            else:
                # アカウント利用不可
                return HttpResponse("アカウントが有効ではありません")
        # ユーザー認証失敗
        else:
            return HttpResponse("ログインIDまたはパスワードが間違っています")
    # GET
    else:
        return render(request, 'login.html')


#ログアウト
@login_required
def Logout(request):
    logout(request)
    # ログイン画面遷移
    return HttpResponseRedirect(reverse('google_app:Login'))


#ホーム
@login_required
def home(request,pk):
    params = {"UserID":request.user,}
    return render(request, "home.html",context=params)

#新規登録
class  AccountRegistration(TemplateView):

    def __init__(self):
        self.params = {
        "AccountCreate":False,
        "account_form": AccountForm(),
        "add_account_form":AddAccountForm(),
        }

    #Get処理
    def get(self,request):
        self.params["account_form"] = AccountForm()
        self.params["add_account_form"] = AddAccountForm()
        self.params["AccountCreate"] = False
        return render(request,"register.html",context=self.params)

    #Post処理
    def post(self,request):
        self.params["account_form"] = AccountForm(data=request.POST)
        self.params["add_account_form"] = AddAccountForm(data=request.POST)

        #フォーム入力の有効検証
        if self.params["account_form"].is_valid() and self.params["add_account_form"].is_valid():
            # アカウント情報をDB保存
            account = self.params["account_form"].save()
            # パスワードをハッシュ化
            account.set_password(account.password)
            # ハッシュ化パスワード更新
            account.save()

            # 下記追加情報
            # 下記操作のため、コミットなし
            add_account = self.params["add_account_form"].save(commit=False)
            # AccountForm & AddAccountForm 1vs1 紐付け
            add_account.user = account

            # 画像アップロード有無検証
            if 'account_image' in request.FILES:
                add_account.account_image = request.FILES['account_image']
            
            # モデル保存
            add_account.save()

            # アカウント作成情報更新
            self.params["AccountCreate"] = True

            #googleカレンダ1年分のデータを取得
            headers = {"Content-Type" : "application/json"}
            user_data = requests.get("http://127.0.0.1:8000/api/user/?user={}".format(account.id),headers=headers)
            dict = json.loads(user_data.content.decode('utf-8'))
            id = dict["results"][0]["id"]
            
            # googleカレンダー情報取得
            lists = get_time(is_registered = False)
            validate_data = {
                "old":int(dict["results"][0]["old"]),
                "sex":dict["results"][0]["sex"],
                "data":lists,
                "datalist":{},
                "user":account.id,
            }
            requests.put("http://127.0.0.1:8000/api/user/{}".format(int(id)),data=json.dumps(validate_data),headers=headers)

        else:
            # フォームが有効でない場合
            print(self.params["account_form"].errors)

        return render(request,"register.html",context=self.params)

google_app/templates/home.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8">
<title></title>
    <!-- <link rel="stylesheet" href='{% static "google_app/css/style.css" %}'/> -->

</head>
<body>
<div id="app"></div>
<p> ログアウトは<a href="{% url 'google_app:Logout' %}">こちら</a>
{% render_bundle 'app'  %}
 </p>

 <!-- refer to JS that was compiled by Laravel Mix -->
<!-- <script type="text/javascript" src="{% static 'build/google_app.js' %}"></script> -->
</body>
</html>

google_app/templates/index.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>自己分析ツール</title>
</head>
<body>
    <div id="app"></div>
{% render_bundle 'app'  %}
</body>
</html>

google_app/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">
<head>
<meta charset="utf-8">
<title></title>
<!-- <link rel="stylesheet" href='{% static "App_Folder_css/style.css" %}'/> -->

</head>
<body>
   <div class="hello">
      <h1>
         自己分析ツールへようこそ!!
      </h1>
   </div>
     <div class="form-wrapper">
        <h1>Sign In</h1>
        <form method="post" action="{% url 'google_app:Login' %}">
           {% csrf_token %}
           <div class="form-item">
       <label for="userid"></label>
       <input type="text" name="userid" placeholder="Username"/>
     </div>
     <div class="form-item">
       <label for="password"></label>
       <input type="password" name="password" required="required" placeholder="Password"></input>
     </div>
     <div class="button-panel">
       <input type="submit" class="button" title="Sign In" value="Sign In"></input>
     </div>
   </form>
   <div class="form-footer">
     <p><a href="{% url 'google_app:register' %}">アカウントを作成</a></p>
     <!-- <p><a href="#">パスワードをお忘れですか？</a></p> -->
   </div>
 </div>
</body>
</html>
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400);

/* fontawesome */
@import url(http://weloveiconfonts.com/api/?family=fontawesome);
[class*="fontawesome-"]:before {
  font-family: 'FontAwesome', sans-serif;
}

/* Simple Reset */
* { margin: 0; padding: 0; box-sizing: border-box; }

/* body */
body {
  background-image: url("/static/profile_bg.png");
  background-repeat:no-repeat;
  background-size: cover;
  color: #5e5e5e;
  height: 1000px;
  font: 400 87.5%/1.5em 'Open Sans', sans-serif;
}
.hello{
   padding: auto;
   margin-top: 10px;
}

/* Form Layout */
.form-wrapper {
  background: #fafafa;
  margin: 3em auto;
  padding: 0 1em;
  max-width: 370px;
}

h1 {
  text-align: center;
  padding: 1em 0;
}

form {
  padding: 0 1.5em;
}

.form-item {
  margin-bottom: 0.75em;
  width: 100%;
}

.form-item input {
  background: #fafafa;
  border: none;
  border-bottom: 2px solid #e9e9e9;
  color: #666;
  font-family: 'Open Sans', sans-serif;
  font-size: 1em;
  height: 50px;
  transition: border-color 0.3s;
  width: 100%;
}

.form-item input:focus {
  border-bottom: 2px solid #c0c0c0;
  outline: none;
}

.button-panel {
  margin: 2em 0 0;
  width: 100%;
}

.button-panel .button {
  background: #f16272;
  border: none;
  color: #fff;
  cursor: pointer;
  height: 50px;
  font-family: 'Open Sans', sans-serif;
  font-size: 1.2em;
  letter-spacing: 0.05em;
  text-align: center;
  text-transform: uppercase;
  transition: background 0.3s ease-in-out;
  width: 100%;
}

.button:hover {
  background: #ee3e52;
}

.form-footer {
  font-size: 1em;
  padding: 2em 0;
  text-align: center;
}

.form-footer a {
  color: #8c8c8c;
  text-decoration: none;
  transition: border-color 0.3s;
}

.form-footer a:hover {
  border-bottom: 1px dotted #8c8c8c;
}
</style>

google_app/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="ja" dir="ltr">

<head>
<meta charset="utf-8">
<title></title>
</head>

<body>

  <div class="form-wrapper">
    <h1>新規登録</h1>
    {% if AccountCreate %}
    <h1>登録完了!</h1>
    <a href="{% url 'google_app:Login' %}">ログインする</a>
    {% else %}
   <form enctype="multipart/form-data" method="post">
   {% csrf_token %}
   <div class="form-item">
    <label for="id_username">ユーザーID:</label>
    <input type="text" name="username" maxlength="150" required="" id="id_username"><br>
    <label for="id_email">メール:</label>
    <input type="email" name="email" maxlength="254" id="id_email">
    <label for="id_password">パスワード:</label><input type="password" name="password" required="" id="id_password">
    <label for="id_old">年齢:</label><input type="number" name="old" value="0" required="" id="id_old">
    <label for="id_sex">性別:</label><select name="sex" required="" id="id_sex">
    <option value="" selected="">---------</option>
    <option value="1">男性</option>
    <option value="2">女性</option>
    <option value="3">Xジェンダー</option>
    </select>
<label for="id_account_image">プロフィール画像:</label><input type="file" name="account_image" accept="image/*" id="id_account_image">

   </div>
   <div class="button-panel">
     <input class="button" type="submit" name="" value="登録">
   </div>
   </form>
   {% endif %}
  </div>
</body>
</html>

<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400);

/* fontawesome */
@import url(http://weloveiconfonts.com/api/?family=fontawesome);
[class*="fontawesome-"]:before {
  font-family: 'FontAwesome', sans-serif;
}

/* Simple Reset */
* { margin: 0; padding: 0; box-sizing: border-box; }

/* body */
body {
  background-image: url("/static/profile_bg.png");
  background-repeat:no-repeat;
  background-size: cover;
  color: #5e5e5e;
  height: 1000px;
  font: 400 87.5%/1.5em 'Open Sans', sans-serif;
}
.hello{
   padding: auto;
   margin-top: 10px;
}

/* Form Layout */
.form-wrapper {
  background: #fafafa;
  margin: 3em auto;
  padding: 0 1em;
  max-width: 370px;
}

h1 {
  text-align: center;
  padding: 1em 0;
}

form {
  padding: 0 1.5em;
}

.form-item {
  margin-bottom: 0.75em;
  width: 100%;
}

.form-item input {
  background: #fafafa;
  border: none;
  border-bottom: 2px solid #e9e9e9;
  color: #666;
  font-family: 'Open Sans', sans-serif;
  font-size: 1em;
  height: 50px;
  transition: border-color 0.3s;
  width: 100%;
}

.form-item input:focus {
  border-bottom: 2px solid #c0c0c0;
  outline: none;
}

.button-panel {
  margin: 2em 0 0;
  padding-bottom: 20px;
  width: 100%;
}

.button-panel .button {
  background: #f16272;
  border: none;
  color: #fff;
  cursor: pointer;
  height: 50px;
  font-family: 'Open Sans', sans-serif;
  font-size: 1.2em;
  letter-spacing: 0.05em;
  text-align: center;
  text-transform: uppercase;
  transition: background 0.3s ease-in-out;
  width: 100%;
}

.button:hover {
  background: #ee3e52;
}

.form-footer {
  font-size: 1em;
  padding: 2em 0;
  text-align: center;
}

.form-footer a {
  color: #8c8c8c;
  text-decoration: none;
  transition: border-color 0.3s;
}

.form-footer a:hover {
  border-bottom: 1px dotted #8c8c8c;
}
</style>